spring:
  application:
    name: web1
  datasource:
    url: jdbc:postgresql://localhost:5432/queue?useUnicode=true&characterEncoding=UTF-8
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true